
    #,------.              ,--.      ,------.,--.   ,--.     ,---. ,--.  ,--.,-----.,------.
    #|  .--. ',---. ,---.,-'  '-.    |  .--. |   `.'   |    '   .-'|  '--'  '  .-.  |  .--. '
    #|  '--'.| .-. | .-. '-.  .-'    |  '--' |  |'.'|  |    `.  `-.|  .--.  |  | |  |  '--' |
    #|  |\  \' '-' ' '-' ' |  |      |  | --'|  |   |  |    .-'    |  |  |  '  '-'  |  | --'
    #`--' '--'`---' `---'  `--'      `--'    `--'   `--'    `-----'`--'  `--'`-----'`--'
    
    
    #Configuration de Furnace par PxModPTDR !
    # me contacter :
    # discord : https://discord.gg/Jg3v9QKhw4
    # mon discord : pxmodptdr

furnace_name : "furnace"
furnace_desc : "§aVous permet de cuire des minerais ! Fait par ROOT PM Shop !"
furnace_use : "/furnace"

# la permission est : furnace.cmd
furnace_perm_message : "§c-§f Vous n'avez pas la permission !"

furnace_cuit : "§2-§f Votre {item} a été cuit !"
furnace_no_cuit : "§c-§f Votre item en main ne peut pas être cuit !"

